pre-commit:
  parallel: true
  commands:
    🎨 format:
      glob: '*.{js,jsx,ts,tsx,md,mdx,html,css,json,yml}'
      run: npx prettier {staged_files} --write && git add {staged_files}
    🧹 lint:
      glob: '*.{js,jsx,ts,tsx,mdx,html,css,yml}'
      run: npx eslint {staged_files} --fix && git add {staged_files}
